# This is a basic workflow to help you get started with Actions

name: CodeCov

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    run:
      runs-on: ubuntu-latest
      env:
        OS: ubuntu-latest
        PYTHON: '3.8'
      steps:
      - uses: checkout@v2
        with:
          fetch-depth: ‘2’

      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Generate Report
        run: |
          pip install -U pip
          pip install coverage pytest 
          pip install git+https://github.com/ohaddoron/common.git
          coverage run -m pytest tests
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
        
